### ISSUE TITLE
MUS extraction unsupported for CNF with either OptUX and MUSx ? 

### ISSUE THREAD

**Issue by fransab** [pysathq/pysat#162]
Hello, 
I am trying to extract MUSes from some unsatisfiable CNFs. I tried to use both OptUx and MUSX and neither of them could provide me with a result.  I am using Windows 10 with Python 3.12 and PySAT 3.1.0. 
I have an unsatisfiable formula U = $(x_1 \vee x_2 )\wedge \neg x_1 \wedge \neg x_2$. The expected MUS would be [0,1,2] given all three clauses are part of it. 

I convert my list of clauses into a CNF object and try to extract a MUS: 
```python
unsat = [[1,2],[-1],[-2]] 
CNF = CNF(from_clauses=cnf)
``` 

When I try calling MUSX on it, it returns me an error: 
```python
musx = MUSX(CNF, verbosity=0)
print( musx.compute() )
``` 
returns:
```
  File c:\users\sabfr\onedrive\thèse\python\tests.py:166
    musx = MUSX(CNF, verbosity=0)

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\examples\musx.py:144 in __init__
    self.oracle = Solver(name=solver, bootstrap_with=formula.hard,

AttributeError: 'CNF' object has no attribute 'hard'
```
OptUX doesn't want to help me either: 
```python
with OptUx(CNF) as optux:
    for mus in optux.enumerate():
        print('mus {0} has cost {1}'.format(mus, optux.cost))
``` 
returns:
```
Exception ignored in: <function OptUx.__del__ at 0x0000028F0F872D40>
Traceback (most recent call last):
  File "C:\Users\sabfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\examples\optux.py", line 303, in __del__
    self.delete()
  File "C:\Users\sabfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\examples\optux.py", line 324, in delete
    if self.hitman:
       ^^^^^^^^^^^
AttributeError: 'OptUx' object has no attribute 'hitman'
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\sabfr\onedrive\thèse\python\tests.py:168
    with OptUx(CNF) as optux:

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\examples\optux.py:230 in __init__
    self.formula.hard = formula.hard[:]

AttributeError: 'CNF' object has no attribute 'hard'
``` 
When I run it the first time in my console, the warning doesn't appear. (but the error does). After that the warning starts appearing. 

I guessed errors would appear because I give them a CNF object instead of WCNF. The documentation provides examples with WNCF but states CNF inputs are also accepted. 
https://pysathq.github.io/docs/html/api/examples/musx.html
https://pysathq.github.io/docs/html/api/examples/optux.html

So I created a wcnf file in DIMACS format that should represent the same formula, unless I got mistaken:
```
p wcnf 4 3 1
1 1 2 0
1 -1 0
1 -2 0
``` 
I set a _top_ weight of 1 and all clauses weights at 1 to ensure every clause is counted as a hard clause. 
I then run MUSX and OptUx the same way, except I give them the corresponding WNCF object as an input.
MUSX returns:
```
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\sabfr\onedrive\thèse\python\tests.py:167
    print( musx.compute() )

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\examples\musx.py:200 in compute
    approx = sorted(self.oracle.get_core())

TypeError: 'NoneType' object is not iterable
```
And OptUx returns:
```
Exception ignored in: <function Solver.__del__ at 0x0000028F0F800220>
Traceback (most recent call last):
  File "C:\Users\sabfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\solvers.py", line 373, in __del__
    self.solver.delete()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete'
Exception ignored in: <function Solver.__del__ at 0x0000028F0F800220>
Traceback (most recent call last):
  File "C:\Users\sabfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\solvers.py", line 373, in __del__
    self.solver.delete()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete'
Exception ignored in: <function Solver.__del__ at 0x0000028F0F800220>
Traceback (most recent call last):
  File "C:\Users\sabfr\AppData\Local\Programs\Python\Python312\Lib\site-packages\pysat\solvers.py", line 373, in __del__
    self.solver.delete()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'delete'
mus [] has cost 0
``` 
Which seems to have returned the null MUS, which is not the expected result.

I saw that solvers such as Minisat22 would require(?) assumption literals to give me an output non None, but in the context of my formula I don't have any assumption literals. 
I managed to compute a MUS using the picomus package (https://fmv.jku.at/picosat/), but would prefer not relying on it as it is unix-dependent. 

Am I doing something wrong ? Or is there an issue with the MUS extraction procedures ? 

Thanks in advance for your help

**Comment by alexeyignatiev** [comment]
Hi @fransab,

The documentation should say (see the list of expected arguments and their types) that the input parameters to `MUSX` and `OptUx` should be weighted formulas. Namely, `MUSX` expects to get a `WCNF` object while `OptUx` wants `WCNFPlus` object. To make your example work, you can make a tiny modification (a call to `.weighted()`, which will create a weighted variant of the formula for you:
```python
>>> from pysat.examples.musx import MUSX
>>> cnf = CNF(from_clauses=[[1, 2], [-1], [-2]])
>>> musx = MUSX(cnf.weighted(), verbosity=0)
>>> musx.compute()
[1, 2, 3]
>>> musx.delete()
>>> with OptUx(cnf.weighted()) as optux:
...     for mus in optux.enumerate():
...         print('mus {0} has cost {1}'.format(mus, optux.cost))
...
mus [1, 2, 3] has cost 3
```

Note that you can call either of these tools on an unweighted `*.cnf` file because the script will call `.weighted()` for you after parsing the file.


As for the WCNF file you are creating, it is incorrect. If you want each clause to be considered as a culprit for unsatisfiability then each clause should be marked as _soft_. This means you should set the top weight (in the preamble) to the sum of weights for all soft clauses, i.e. it should be 4 rather than 1. Currently, all the clauses in the file are made _hard_, hence the cores MUSX and OptUx are getting are empty.

I hope this helps,
Alexey

**Comment by fransab** [comment]
Thanks for your help @alexeyignatiev . 
I guess it would be nice for these MUS extractors to directly support formulas in CNF formulas, given the minimal modification required, unless specific situations could return an unwanted result ? 
Sorry for my misunderstanding of the WCNF format and thanks for your clarification, I understand why it works now. 

Francesco
