### ISSUE TITLE
pysat doesn't build/install clean from checkout

### ISSUE THREAD

**Issue by gavinp** [pysathq/pysat#185]
```
$ git clone git@github.com:pysathq/pysat.git
$ cd pysat && pip install -e .
```

And sadness ensues. The build fails quickly.

Redoing it verbosely, I saw:

```
  ...
  building 'pysolvers' extension
  creating /tmp/tmpcun3vbbp.build-temp/solvers
  x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -Isolvers -I/home/gavin/venvs/python-sat/include -I/usr/include/python3.12 -c solvers/pysolvers.cc -o /tmp/tmpcun3vbbp.build-temp/solvers/pysolvers.o -std=c++11 -Wall -Wno-deprecated -DWITH_CADICAL103 -DWITH_CADICAL153 -DWITH_CADICAL195 -DWITH_GLUECARD30 -DWITH_GLUECARD41 -DWITH_GLUCOSE30 -DWITH_GLUCOSE41 -DWITH_GLUCOSE421 -DWITH_LINGELING -DWITH_MAPLECHRONO -DWITH_MAPLECM -DWITH_MAPLESAT -DWITH_MERGESAT3 -DWITH_MINICARD -DWITH_MINISAT22 -DWITH_MINISATGH
  solvers/pysolvers.cc:22:10: fatal error: cadical103/cadical.hpp: No such file or directory
     22 | #include "cadical103/cadical.hpp"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-vd8vwgou/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
      subprocess.check_call(cmd, env=_inject_macos_ver(env))
    File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/x86_64-linux-gnu-g++', '-fno-strict-overflow', '-Wsign-compare', '-DNDEBUG', '-g', '-O2', '-Wall', '-fPIC', '-Isolvers', '-I/home/gavin/venvs/python-sat/include', '-I/usr/include/python3.12', '-c', 'solvers/pysolvers.cc', '-o', '/tmp/tmpcun3vbbp.build-temp/solvers/pysolvers.o', '-std=c++11', '-Wall', '-Wno-deprecated', '-DWITH_CADICAL103', '-DWITH_CADICAL153', '-DWITH_CADICAL195', '-DWITH_GLUECARD30', '-DWITH_GLUECARD41', '-DWITH_GLUCOSE30', '-DWITH_GLUCOSE41', '-DWITH_GLUCOSE421', '-DWITH_LINGELING', '-DWITH_MAPLECHRONO', '-DWITH_MAPLECM', '-DWITH_MAPLESAT', '-DWITH_MERGESAT3', '-DWITH_MINICARD', '-DWITH_MINISAT22', '-DWITH_MINISATGH']' returned non-zero exit status 1.
```

Did I miss the build instructions? Where are these dependencies exposed?

**Comment by alexeyignatiev** [comment]
There are no external dependencies here as the files are shipped with the toolkit. But it looks like some of the scripts used for compilation fail to run (they should move the source files in the expected directories). I can check when I get back from holidays to my computer.

**Comment by gavinp** [comment]
I'm happy to look at this; I'm enthusiastic, in fact. Any particular pointers? I'm presuming it's a failure to run something from solvers/prepare.py, but I'm not sure. A few minutes sharing ideas is useful; esp if it's at a configuration at works for this.

Otherwise, enjoy your vacation! Thanks.

**Comment by alexeyignatiev** [comment]
Thank you and apologies for taking time with the reply. Yes, the installation process should necessarily run `do()` from `prepare.py` with the list of solvers to build (you can see how it is handled in `setup.py`). I am not sure at this point why it fails to run in your case to be honest.

**Comment by gavinp** [comment]
See issue #189 which seems to have been a dup of this, although with way better cut-and-paste of the failure experience.
