### ISSUE TITLE
Ctrl+C causes Python interpreter with pysat loaded to exit not gracefully yield an exception

### ISSUE THREAD

**Issue by GregoryMorse** [pysathq/pysat#53]
Any time Ctrl+C is used to interrupt running code, it will throw a KeyboardInterrupt.  But something is going on after doing SAT solving which causes it to not work all of the time and instead just exit the interpreter.  Either this indicates Ctrl+C is being explicitly caught and inappropriately dealt with or some type of cleanup code is probably cause a crash.

**Comment by alexeyignatiev** [comment]
Yep, that's a problem. It used to work properly a few months ago but now this is what happens. I need to investigate what causes it.

**Comment by alexeyignatiev** [comment]
OK, I think this concrete issue seems to be caused by the signal handling, which works fine on other systems, e.g. on Linux or MacOS. Since I don't have access to Windows, it is kind of problematic for me to investigate and so to fix it. :)

**Comment by dulanov** [comment]
I have access to Windows, will try to reproduce it.

**Comment by alexeyignatiev** [comment]
Thanks, @dulanov!

**Comment by dulanov** [comment]
So, `pip install python-sat` directly doesn't work on Windows by me, I'll analyze it deeper and maybe create a ticket:

```shell
...
      C:\Users\ABC\AppData\Local\Temp\pip-install-i8zkex_7\python-sat_d5feacf086464b6a84d8a0a15faaa9e5\solvers\cadical103\internal.hpp(21): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "unistd.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
...
```

Here `unistd.h` is POSIX related file existed only on UNIX systems, not on Windows.

But `python setup.py install` works, so I download some benchmarks from SAT Competition 2023, exactly [this one](https://benchmark-database.de/file/004b0f451f7d96f6a572e9e76360f51a) and after some minutes of execution try to break it 
 with `Ctrl+C`:

```shell
(.venv) PS C:\Workspace\References\pysathq-pysat\examples> python.exe lbx.py -d -e all -s glucose3 -vv 004b0f451f7d96f6a572e9e76360f51a-spg_420_280.cnf.xz
Traceback (most recent call last):
  File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 584, in <module>
    for i, mcs in enumerate(mcsls.enumerate()):
  File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 301, in enumerate
    mcs = self.compute()
          ^^^^^^^^^^^^^^
  File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 284, in compute
    self._filter_satisfied(update_setd=True)
  File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 374, in _filter_satisfied
    setd = setd.union(set(cl))
    ^^^^
KeyboardInterrupt
```

@GregoryMorse  It seems to me that this problem no longer exists.

**Comment by alexeyignatiev** [comment]
Installation from pip should work on the platforms which I compiled it for (there are a few binary wheels provided).

As for the curl+c issue, it got interrupted while in Python (not the "solvers" C extension). By any chance, can you try it on hard CNF instances where a SaT call takes a lot of time so that you interrupt it during a SAT call?

**Comment by dulanov** [comment]
> there are a few binary wheels provided

This is strange because `pip install` imidiatelly start to recompile all dependencies from source.

[log.txt](https://github.com/pysathq/pysat/files/13692403/log.txt)

**Comment by dulanov** [comment]
>  By any chance, can you try it on hard CNF instances where a SaT call takes a lot of time so that you interrupt it during a SAT call?

It was exactly hard CNF formula (89Mb) and I tried several times, but I will try to more deeply analyze the moment of interrupt, ok.

**Comment by alexeyignatiev** [comment]
> > there are a few binary wheels provided
> 
> 
> 
> This is strange because `pip install` imidiatelly start to recompile all dependencies from source.
> 
> 
> 
> > `ERROR: Could not build wheels for python-sat, which is required to install pyproject.toml-based projects`
> 
> 
> 
> [log.txt](https://github.com/pysathq/pysat/files/13692403/log.txt)
> 
> 

Well, I guess it means you are using a different platform. 🙂

**Comment by alexeyignatiev** [comment]
> >  By any chance, can you try it on hard CNF instances where a SaT call takes a lot of time so that you interrupt it during a SAT call?
> 
> 
> 
> It was exactly hard CNF formula (89Mb) and I tried several times, but I will try to more deeply analyze the moment of interrupt, ok.

Sure, but the traceback log you attached clearly shows the execution was interrupted in Python. It would help to catch it when it is inside one of the solver's code.

**Comment by dulanov** [comment]
I see, s.12 isn't supported yet.

![image](https://github.com/pysathq/pysat/assets/65018268/6d4b5c28-cb46-4507-9310-4e04bd504b5a)

**Comment by alexeyignatiev** [comment]
Yes, it's not yet supported. It can be supported if @rjungbeck can compile pypblib for Python 3.12. 🙂

**Comment by dulanov** [comment]
> be supported if @rjungbeck can compile pypblib for Python 3.12

May be a good task to automate it using GitHub Actions ;)

**Comment by dulanov** [comment]
> > > By any chance, can you try it on hard CNF instances where a SaT call takes a lot of time so that you interrupt it during a SAT call?
> > 
> > 
> > It was exactly hard CNF formula (89Mb) and I tried several times, but I will try to more deeply analyze the moment of interrupt, ok.
> 
> Sure, but the traceback log you attached clearly shows the execution was interrupted in Python. It would help to catch it when it is inside one of the solver's code.

I found pretty simple but not trivial [hard CNF](https://github.com/arminbiere/satch/blob/master/cnfs/prime65537.cnf) borrowed from https://github.com/arminbiere/satch repository and this error now is reproducable:

```shell
(.venv) PS C:\Workspace\References\pysathq-pysat\examples> python.exe lbx.py -d -e all -s glucose3 -vv .\cnfs\prime65537.cnf
(.venv) PS C:\Workspace\References\pysathq-pysat\examples> $LASTEXITCODE
-1073741784
```

**Comment by alexeyignatiev** [comment]
Thanks, @dulanov. It would be nice to understand what causes this on Windows. I understand it may be difficult.

**Comment by GregoryMorse** [comment]
I'd guess the signal handler code is buggy on Windows and crashes.  The easiest way to track the issue down if being able to reproduce it is to attach a debugger and see where it crashes.  It could potentially be a concurrent programming issue and exist on Linux as well just be highly unlikely there by how signal handler is scheduled.

**Comment by GregoryMorse** [comment]
Also this looks like a bug in glucose from the Python stack trace.

**Comment by dulanov** [comment]
> Also this looks like a bug in glucose from the Python stack trace.

Interesting, will try with more fresh Glucose (4+) as well, because Glucose 3 is pretty old, and also if you right, `KeyboardInterrupt` should work with other solvers.

**Comment by rjungbeck** [comment]
> > be supported if @rjungbeck can compile pypblib for Python 3.12
> 
> May be a good task to automate it using GitHub Actions ;)

The build process itself is automated via AppVeyor (similar to Github Axctions) . But it requires that the new target environment (Python 3.12) is configured in appveyor.yml, which must be done manually.

**Comment by rjungbeck** [comment]
> Yes, it's not yet supported. It can be supported if @rjungbeck can compile pypblib for Python 3.12. 🙂

I have made a Python 3.12 version of pypblib (https://github.com/rjungbeck/pypblib/releases/download/pypblib-v1.0.439/pypblib-0.0.4-cp312-cp312-win_amd64.wh)

**Comment by alexeyignatiev** [comment]
Thanks so much, @rjungbeck! I've now included this configuration in `appveyor/instdep.py`.

**Comment by dulanov** [comment]
> > Also this looks like a bug in glucose from the Python stack trace.
> 
> Interesting, will try with more fresh Glucose (4+) and also if you right, `KeyboardInterrupt` should work with other solvers.

Error is reproducable with all solvers including minisat (by default).

I found a place in `solvers/pysolvers.cc` and after local change in method `py_glucose3_solve` start to receive also on Windows `KeyboardInterrupt` explicitly:

![image](https://github.com/pysathq/pysat/assets/65018268/0b16a025-62c2-48a4-8030-00d1661736fa)

![image](https://github.com/pysathq/pysat/assets/65018268/88ba28ac-cad0-4d75-9353-11669d83813f)

where wxit Code `0xC000013A` exactly means that the application terminated as a result of a `CTRL+C`.

**Comment by GregoryMorse** [comment]
> > > Also this looks like a bug in glucose from the Python stack trace.
> > 
> > 
> > Interesting, will try with more fresh Glucose (4+) and also if you right, `KeyboardInterrupt` should work with other solvers.
> 
> Error is reproducable with all solvers including minisat (by default).
> 
> I found a place in `solvers/pysolvers.cc` and after local change in method `py_glucose3_solve` start to receive `KeyboardInterrupt` also on Windows:
> 
> ![image](https://private-user-images.githubusercontent.com/65018268/294552493-0b16a025-62c2-48a4-8030-00d1661736fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Nzk5NTMsIm5iZiI6MTcwNDQ3OTY1MywicGF0aCI6Ii82NTAxODI2OC8yOTQ1NTI0OTMtMGIxNmEwMjUtNjJjMi00OGE0LTgwMzAtMDBkMTY2MTczNmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE4MzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Yjc0NzQ1YzdmYzkxOTdjYzM0MTdmZjM4NGFmZDk0NTJmNWE4ZjMxMjUyODlmZDdiYWUzMzBiYmI5NGNlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-knv2h2A07spqqWX08DiwBZ-ASiMbdTjljS1_TGled4)
> 
> ```shell
> (.venv) PS C:\Workspace\References\pysathq-pysat> python.exe .\examples\lbx.py -d -e all -s glucose3 -vv .\examples\cnfs\prime65537.cnf
> Traceback (most recent call last):
>   File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 584, in <module>
>     for i, mcs in enumerate(mcsls.enumerate()):
>   File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 301, in enumerate
>     mcs = self.compute()
>           ^^^^^^^^^^^^^^
>   File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 285, in compute
>     self._compute()
>   File "C:\Workspace\References\pysathq-pysat\examples\lbx.py", line 408, in _compute
>     if self.oracle.solve(assumptions=self.ss_assumps + self.bb_assumps + [self.setd[i]]):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Workspace\References\pysathq-pysat\.venv\Lib\site-packages\python_sat-0.1.8.dev12-py3.12-win-amd64.egg\pysat\solvers.py", line 564, in solve 
>     return self.solver.solve(assumptions)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Workspace\References\pysathq-pysat\.venv\Lib\site-packages\python_sat-0.1.8.dev12-py3.12-win-amd64.egg\pysat\solvers.py", line 2827, in solve
>     self.status = pysolvers.glucose3_solve(self.glucose, assumptions,
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyboardInterrupt
> (.venv) PS C:\Workspace\References\pysathq-pysat> $LASTEXITCODE
> -1073741510
> ```
> 
> where exit Code `0xC000013A` exactly means that the application terminated as a result of a `CTRL+C`.
> 
> Without this change `glucose4` still exit silently:
> 
> ```shell
> (.venv) PS C:\Workspace\References\pysathq-pysat> python.exe .\examples\lbx.py -d -e all -s glucose4 -vv .\examples\cnfs\prime65537.cnf
> (.venv) PS C:\Workspace\References\pysathq-pysat> $LASTEXITCODE
> -1073741784
> ```
> 
> P.S. File `pysolvers.cc` contains a large amount of duplicate code for each solver and is an excellent candidate for a code generator, I will not change it yet, so as not to break the logic on other platforms.

Disabling the signal handler causes a pass through but it's not a good solution at all.  Obviously something with the use of PyOS_setsig is the issue.

One known issue is use of import_array() for numpy.  Apparently it sets up signal handlers and can throw off the expected behavior.  

With a simple debug build and debugging session this is an easy solve.  Just pinpoint the root cause of the crash and it won't be hard to back track abd figure out the code issue.  So this discussion seems a bit silly.  Disabling the signal handler is not a fix.  This should be a portable Windows supported API.  Some small detail is misimplemented.  It's likely buggy on Linux too, it's just there for whatever reason it doesn't crash.  This is with high likelihood a universal bug from a clean coding practice standpoint.  Microsoft tends to be more standards compliant these days than anyone else.  So stability on Windows or MSVC means stability on Linux or GCC.  But the reverse is never true.  In fact, despite all the hate towards Microsoft and praise towards Linux over the years, the best programmers are invariably always the ones who can write portable code.  So again to conclude, this project has poor signal handling code which requires manual debugging to solve.

**Comment by dulanov** [comment]
@Gregory Morse I ended up in a rabbit hole ;) Apparently, we are dealing with the standard problem of processing kernel signals using `setjmp / longjmp`. The behavior in this case is non-deterministic and varies from platform to platform.

`Invoking longjmp from a nested signal handler is [undefined](https://en.wikipedia.org/wiki/Undefined_behavior).` (from [Wikipedia](https://en.wikipedia.org/wiki/Setjmp.h))

[1] https://stackoverflow.com/questions/7334595/longjmp-out-of-signal-handler
[2] https://mingw-users.narkive.com/mRVHRtGT/longjmp-in-signal-handler

**Comment by GregoryMorse** [comment]
> @GregoryMorse I ended up in a rabbit hole ;) Apparently, we are dealing with the standard problem of processing kernel signals using `setjmp / longjmp`. The behavior in this case is non-deterministic and varies from platform to platform because `Invoking longjmp from a nested signal handler is undefined` (from [Wikipedia](https://en.wikipedia.org/wiki/Setjmp.h)).
> 
> [1] https://stackoverflow.com/questions/7334595/longjmp-out-of-signal-handler [2] https://mingw-users.narkive.com/mRVHRtGT/longjmp-in-signal-handler

Very nice find.  So undefined behavior seems to work on Linux not on Windows.  That is why I often consider source quality as higher when a shared source works on both which is the case for this repo.

So it should be redesigned to not use long jump it sounds like.  I generally think setting a flag in the signal handler and periodically checking the flag in all potentially long running operations is the safest way to go.

**Comment by dulanov** [comment]
@alexeyignatiev looks like wrong usage of `longjump` from sighandler on sigaltstack, but it was make some years ago with https://github.com/pysathq/pysat/commit/cf182bd8dc558d044868f8a7849147155ac0e1d6

**Comment by alexeyignatiev** [comment]
Thanks for the finding, @dulanov. The question is why I decided to replace POSIX functions that I first used with C standard library alternative ones. 🙂 May 2018 was so long ago (even before a working Windows version) that it looks hard to understand now but there must have been a justification.
